# hostPath 유형을 사용하는 영구볼륨
# hostPath는 단일 노드 테스트 환경에서만 작동한다.
# 멀티 노드 환경에서는 사용 불가.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity: # 다양한 pod에서 사용할 수 있는 capacity를 제어하기 원할때
    storage: 1Gi # 저장용량
  volumeMode: Filesystem # Filesystem Block,
  storageClassName: standard # default storage class
  accessModes:
    - ReadWriteOnce # 단일 노드에 대해서만 I/O를 허용
    # - ReadOnlyMany 읽기 전용이지만 여러 노드에서 I/O 허용
    # - ReadWriteMany 여러 노드에서 I/O 허용
  hostPath:
    path: /data
    type: DirectoryOrCreate # 호스트 경로가 없으면 생성
